import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/lib/trpc-provider";
import { SiteHeader } from "@/components/site-header"; // Import the new header
import { SiteFooter } from "@/components/site-footer"; // Import the footer
import { AuthProvider } from "@/hooks/use-auth"; // Import the AuthProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TRPCReactProvider>
          <AuthProvider> {/* Wrap children with AuthProvider */}
            <div className="flex min-h-svh flex-col">
              {/* <SiteHeader /> */}
              <main className="flex flex-1 flex-col">
                {children}
              </main>
              <SiteFooter />
            </div>
          </AuthProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
